// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606155116_v1.12")]
    partial class v112
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Clientes", b =>
                {
                    b.Property<int>("ClientesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientesID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("ClientesID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("backend.Models.Endereco", b =>
                {
                    b.Property<int>("EnderecoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EnderecoID"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidosID")
                        .HasColumnType("integer");

                    b.HasKey("EnderecoID");

                    b.HasIndex("PedidosID")
                        .IsUnique();

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("backend.Models.ItensMenu", b =>
                {
                    b.Property<int>("ItensMenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItensMenuID"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Preco")
                        .HasColumnType("integer");

                    b.HasKey("ItensMenuID");

                    b.ToTable("ItensMenu");
                });

            modelBuilder.Entity("backend.Models.Mesa", b =>
                {
                    b.Property<int>("MesaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MesaID"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<bool>("Disponibilidade")
                        .HasColumnType("boolean");

                    b.HasKey("MesaID");

                    b.ToTable("Mesa");
                });

            modelBuilder.Entity("backend.Models.Pagamentos", b =>
                {
                    b.Property<int>("PagamentosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PagamentosID"));

                    b.Property<DateTime>("PagamentoData")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PagamentoMetodo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidosID")
                        .HasColumnType("integer");

                    b.HasKey("PagamentosID");

                    b.HasIndex("PedidosID")
                        .IsUnique();

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("backend.Models.Pedidos", b =>
                {
                    b.Property<int>("PedidosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PedidosID"));

                    b.Property<int>("ClientesID")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientesID1")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MesaID")
                        .HasColumnType("integer");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPedido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValorTotal")
                        .HasColumnType("integer");

                    b.HasKey("PedidosID");

                    b.HasIndex("ClientesID");

                    b.HasIndex("ClientesID1");

                    b.HasIndex("MesaID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("backend.Models.PedidosItensMenu", b =>
                {
                    b.Property<int>("PedidoID")
                        .HasColumnType("integer");

                    b.Property<int>("ItensMenuID")
                        .HasColumnType("integer");

                    b.Property<int>("PrecoUnit")
                        .HasColumnType("integer");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("PedidoID", "ItensMenuID");

                    b.HasIndex("ItensMenuID");

                    b.ToTable("PedidosItensMenu");
                });

            modelBuilder.Entity("backend.Models.Endereco", b =>
                {
                    b.HasOne("backend.Models.Pedidos", "Pedidos")
                        .WithOne("Endereco")
                        .HasForeignKey("backend.Models.Endereco", "PedidosID");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("backend.Models.Pagamentos", b =>
                {
                    b.HasOne("backend.Models.Pedidos", "Pedidos")
                        .WithOne("Pagamentos")
                        .HasForeignKey("backend.Models.Pagamentos", "PedidosID");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("backend.Models.Pedidos", b =>
                {
                    b.HasOne("backend.Models.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("ClientesID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("backend.Models.Clientes", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ClientesID1");

                    b.HasOne("backend.Models.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("MesaID");

                    b.Navigation("Clientes");

                    b.Navigation("Mesa");
                });

            modelBuilder.Entity("backend.Models.PedidosItensMenu", b =>
                {
                    b.HasOne("backend.Models.ItensMenu", "ItensMenu")
                        .WithMany("PedidosItensMenus")
                        .HasForeignKey("ItensMenuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Pedidos", "Pedido")
                        .WithMany("PedidosItensMenus")
                        .HasForeignKey("PedidoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItensMenu");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("backend.Models.Clientes", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("backend.Models.ItensMenu", b =>
                {
                    b.Navigation("PedidosItensMenus");
                });

            modelBuilder.Entity("backend.Models.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("backend.Models.Pedidos", b =>
                {
                    b.Navigation("Endereco");

                    b.Navigation("Pagamentos");

                    b.Navigation("PedidosItensMenus");
                });
#pragma warning restore 612, 618
        }
    }
}
